spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barter_db
    username: joelhernandez
    password: qsT53aybjhUoRc
  jpa:
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        temp:
          use_jdbc_metadata_defaults: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

server:
  port: 8081